### PR TITLE
Mathematical priority; test for create task trigger

### PR DESCRIPTION
**Pull request by Majed6**
* [Fix] Sample in find_task.js.
* [New] Support nerdamer symbolic math expressions for task priority.
* [Fix] Upgraded dependencies.

### CODE REVIEW

**Comment by gabrielkrell** [comment]
@crookedneighbor can this be merged?

**Comment by crookedneighbor** [comment]
I'm no longer a core contributor to the habitica project, so it's not up to me.

**Comment by gabrielkrell** [comment]
Thanks for the quick response.  Do you know who I can reach out to?

**Comment by paglias** [comment]
Hi @gabrielkrell and @Majed6, we're happy to merge PRs from the community but @crookedneighbor fully managed the extension before so right now I don't have access to the Zapier extension to update it if necessary. 

@crookedneighbor when you have some free time could you post in Slack anything needed to manage this extension?

**Comment by ianrandmckenzie** [comment]
@paglias – did you ever get everything you needed to manage the extension? I was hoping to contribute, but don't want to put in the effort if my PR(s) is/are going to linger.

**Comment by paglias** [comment]
Hi @ianrandmckenzie , we're currently looking into re-enabling and updating the Zapier integration, should have more news by the end of the week

**Comment by ianrandmckenzie** [comment]
Awesome. Thanks for the update, Matteo.

**Comment by paglias** [comment]
Just an heads up @Majed6 that we'll discuss this on Wednesday and I'll let you know as soon as we have a decision

**Comment by Majed6** [comment]
@paglias Thanks for the heads up. Looking forward to hearing back from you. The Zapier integration is the main reason I'm able to continue enjoying and benefiting from Habitica. 

This integration helps me reduce friction. For example :

- When I add an article to my reading list app , a modified version of this integration adds it as a to-do and calculate the the task difficulty based on the characters count of that article. 

- When I'm done reading it from my reading list app, the integration scores the task as done.

- I use a more complex to-do app and through this integration I'm able to sync my weekly tasks between it and Habitica. When I weekly plan a to-do there , it adds it to Habitica. When a to-do is done, the integration scores the task as done in Habitica. 

- When something is overdue, the integration scores up a reward that deducts some of my balance in Habitica. 


If we're afraid of Zombie users, I highly recommend implementing an API gateway like Google that deactivate API keys based on user activity. In our case the only activity we would account for is human interaction through the two official Habitica channels, the website and the mobile apps. 

I really appreciate and enjoy the community aspect of Habitica but it's the friction between my life (lifestyle, tools, equipments) and Habitica that bothers me. The more we lower that friction, the higher the retention becomes. I believe that this integration is one of the ways that we can lower the discipline required to discipline ourselves through Habitica. 😉

**Comment by paglias** [comment]
Sorry again for the delay but our meeting that should have happened yesterday has been moved by 1 week

**Comment by Majed6** [comment]
@paglias Any news ?

**Comment by paglias** [comment]
Sorry again for the delay but we're a very small team and sometimes it takes a bit more time than expected :) We've decided to support Zapier but don't have an ETA on when the integration will be available again. That being said if you want to push any other PR in the meantime feel free to do so and it'll be merged as soon as possible

**Comment by Alys** [comment]
@Majed6 Ignore the conflicts that have just appeared for this.

**Comment by Alys** [comment]
@Majed6 I've merged this but without support for nerdamer for the reasons I've described in this commit: https://github.com/HabitRPG/habitica-zapier/commit/a7f8b57ad2b5ef237b58ceac5d28c4dfab4aec3e
In brief, I don't want too many dependencies in this project (at least not right now while I'm still finding my feet here). I'm happy to discuss the benefits of it a bit later.

I do however very much appreciate the rest of the support for priority/difficult and especially our first test! If you give me your Habitica User ID, I'll award you credit towards a Comrade tier.

Thank you for your work on this and for your legendary patience.

**Comment by Alys** [comment]
@Majed6 @gabrielkrell @ianrandmckenzie Please see the new information in this repo's [README](https://github.com/HabitRPG/habitica-zapier/) linking to a tiny bit of wiki documentation and the new [Aspiring Zapier Comrades](https://habitica.com/groups/guild/f144f026-cf47-4ab0-a857-0e80ee43d4fd) guild. If you'd like to join that guild for discussions about developing and testing the integration, you'd be very welcome. Especially since I'm new to Zapier integrations and I have questions right now. :)

**Comment by Alys** [comment]
I've given Tier 1 as a Comrade to @Majed6 / b6a874c8-e81a-42b7-bbe7-a571ed87abd4 for adding support for priorities, and partial credit towards Tier 2 for the create_task test.

**Pull request merged**
