### PR TITLE
Add frequency to habits

### LINKED ISSUE #6: allow frequency to be specified for Habits
Habits have a `frequency` field that defines how often the +/- counters are set to zero. The value can be `daily`, `weekly`, or `monthly`

The `creates/create_task.js` script should have support for frequency for Habits.

### PR DESCRIPTION
**Pull request by Majed6**
Close [Issue 6](https://github.com/HabitRPG/habitica-zapier/issues/6)

### CODE REVIEW

**Comment by Alys** [comment]
Thanks for this! I'll try to get it reviewed and merged this week. If it's still waiting this time next week, please remind me!

**Comment by Alys** [comment]
Thank you! Tier 2 awarded. I'll post here when this has been pushed to Zapier, which I'm hoping I can do in a day or two.

**Comment by Majed6** [comment]
Yipee! Thanks a lot for the merge and the award.

**Comment by Alys** [comment]
That's live now in version 2.2.1 of the [Habitica Beta](https://zapier.com/developer/public-invite/85683/5d6e78b8fca526b751e69df3c12dc350/).  Thanks again!

**Comment by Majed6** [comment]
@Alys and the team Would you be interested in a continuous deployment pipeline ? Something like Deploy to Zapier when I tag a commit as ver:XXXX . Would be enjoyable to do. Just give me the conditions on which to deploy. 

In Zapier we have the following important actions:
- `push` : Build and upload the current app (Build).
- `promote` : Promotes a specific version to public access.
  - Not currently relevant since we're still on beta stage.  
- `migrate` : Migrates users from one version of your app to another. Can be done with `percent` of users
- `deprecate` : Marks a non-production version of your app as deprecated, with removal by a certain date.

How would you like to manage these actions?  Could be as simple as "When I tag a commit with a version, push to Zapier" or as complex as:
- Push on commit version tag and Migrate 20% of users to the new version
- Promote latest tag on release branch push
- Deprecate when promoting from major to major tag.

I suggest starting simple and as soon as we have a clearer picture of the integration change/adoption rate, we could get more complex.

**Comment by Alys** [comment]
I think that's a lovely idea! Thank you for offering! I think initially it would be best to keep it simple as you suggest and do "When I tag a commit with a version, `push` to Zapier". That's a safe action as it wouldn't affect any existing users.

@paglias What do you think?

**Comment by paglias** [comment]
starting with `push` looks like a good idea, @Majed6 let us know if you need anything done from us to set it up

**Pull request merged**
