### PR TITLE
Refactoring proposal

### LINKED ISSUE #5: ensure that creates/create_task.js supports all types of Daily repeat options
I haven't looked into this closely but I think the repeat options for Dailies in `creates/create_task.js` don't contain all the options that are available in the task edit form in habitica.com

If someone would like to investigate that and add some or all of the missing options (if any), please do.

If you want to do a pull request to add just one or two missing options, that's fine. Comment here to say what you want to add and write "partial fix for #[issue number]" in the PR.

### PR DESCRIPTION
**Pull request by Majed6**
Hi,

I find adding more functionalities to create_task.js very annoying because of how the code is structured. Too many unneeded nested functions. To me it's a bit confusing. I would like to propose the structure in this PR. I find it a bit easier to follow. It has this structure:
```
creates/
└── create_task/
    ├── index.js
    └── input_fields/
        ├── index.js
        ├── daily.js
        ├── habit.js
        ├── todo.js
        └── reward.js
```
I believe this structure would scale up cleanly as we add outputFields, sample, and other `creates` attributes.

While digging deeper into the code I noticed some spelling mistakes and I fixed them in this PR as well. 

I also noticed that weeklies's repeat on days did not work and was sending `repeat__s: true`, which is a proper nested object syntax in output and not the input , instead of `repeat: { s: true }`. I clarified that the default value for repeat on days API was true / yes.

I added support for monthlies and yearlies, to close #5 .

Tell me what you think of the structure and what should I improve. If you prefer the old structure, I'm totally ok with applying the other changes to it instead.

Looking forward to your feedback,
Majed

### CODE REVIEW

**Comment by Alys** [comment]
I like this idea! It does seem clearer.

@paglias What do you think?

**Comment by paglias** [comment]
Looks good to me, @Majed6 is this in progress or ready to be merged? In that case it superseded #13 ?

**Comment by Majed6** [comment]
Ready to be merged. Thank you guys.

**Comment by Alys** [comment]
I've awarded you Tier 3 for this and also partial credit towards Tier 4. Thanks again!

**Pull request merged**
